### ISSUE TITLE
TypeError when adding an item to Cart

### ISSUE THREAD

**Issue by trashken** [pevey/sveltekit-medusa-starter#5]
{
  id: 'awZtmm4DT9WC7ikp9JKGB',
  type: 'response',
  timestamp: '2023-10-17T08:44:49.794Z',
  url: 'http://localhost:9000/store/carts',
  status: 400,
  statusText: 'Bad Request'
}
TypeError: Cannot read properties of undefined (reading 'id')
    at MedusaClient.addToCart (C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/node_modules/sveltekit-medusa-client/dist/index.js:338:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async add (C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/src/routes/cart/+page.server.ts:9:18)
    at async Module.handle_action_json_request (C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:57:16)
    at async resolve (C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/node_modules/@sveltejs/kit/src/runtime/server/respond.js:415:18)
    at async Object.handle (C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/src/hooks.server.ts:7:20)
    at async Module.respond (C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:20)
    at async file:///C:/Users/kenne/sveltekit/sveltekit-medusa-starter-main/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:506:22

**Comment by pevey** [comment]
First things I would try:

- Incognito mode  or deleting your existing cookies
- Use WSL.  Medusa is not meant to run on Windows.

**Comment by aidanswank** [comment]
I got the same error when adding to cart. Tried incognito but no difference. 
Im running medusa server on MacOS 12.5. Node v18.17.0

**Comment by aidanswank** [comment]
Im also using medusajs 6.1.8
